# Generated by Django 5.0.4 on 2024-04-28 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_energydrinks_feminiecare_healthcaredevices_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Energydrinks",
        ),
        migrations.DeleteModel(
            name="Feminiecare",
        ),
        migrations.DeleteModel(
            name="Healthcaredevices",
        ),
        migrations.DeleteModel(
            name="Healthsupplements",
        ),
        migrations.DeleteModel(
            name="Herbalpreperations",
        ),
        migrations.DeleteModel(
            name="Personalcare",
        ),
        migrations.DeleteModel(
            name="Prescriptions",
        ),
    ]
